### PR TITLE
GitHub Enterprise support

### PR DESCRIPTION
**Pull request by mattbrictson**
This PR adds GitHub Enterprise support, in a way that should *just work* provided your `.netrc` is set up correctly. You can now also explicitly specify your GitHub Enterprise endpoint using the `--github` option, like this:

```
--github=https://github.mycompany.com/organization/project
```

@SimenB Can you test this using your GH Enterprise setup?

### CODE REVIEW

**Comment by SimenB** [comment]
Awesome! sure I can test, but how do I install from GH? 😆 

`gem install mattbrictson/chandler#github-enterprise` doesn't work (that's how an `npm install` would be)

**Comment by mattbrictson** [comment]
One way is to clone the project, switch to the branch and run `rake install`. If that doesn't work I can publish an alpha version to Rubygems.

**Comment by mattbrictson** [comment]
@SimenB Do you have `github.schibsted.io` in your `~/.netrc`?

**Comment by SimenB** [comment]
Yup, if I change something with the entry `curl -n` gives med 401 instead of 404. I don't know why chandler get's 401...

**Comment by mattbrictson** [comment]
Hmm. It seems like authentication must be working if the code has gotten that far. Unfortunately I'm not sure there is a debug log that will help. Maybe you could check the Octokit [documentation](https://github.com/octokit/octokit.rb) and [issues](https://github.com/octokit/octokit.rb/issues) to see if there any known problems with obtaining releases with the GitHub Enterprise API?

**Comment by SimenB** [comment]
I don't think auth is correct inside chandler. If I mess up the pw in netrc, I get 401 with `curl` as well, and chandler fails at the exact same spot

**Comment by SimenB** [comment]
Do you have a minimal repro that just tries to fetch releases (using the url above) i could run? If that doesn't work, i can open an issue with octokit

**Comment by mattbrictson** [comment]
@SimenB I've pushed a new commit to this branch that may solve the netrc auth problem. Can you redo `rake install` using the latest code and see if that works?

**Comment by SimenB** [comment]
Will try it out when I get home! A couple of hours 😄

**Comment by SimenB** [comment]
It works!

image

**Comment by mattbrictson** [comment]
Great! I will tidy up the test coverage and publish a release in the next week or so.

**Comment by SimenB** [comment]
@mattbrictson Could you do a release of this? 😄

**Comment by mattbrictson** [comment]
✅ Chandler 0.6.0 released

**Pull request merged**
