### PR TITLE
Add --tag-prefix option

### LINKED ISSUE #3: Nothing happens?
Trying out chandler on a project and basically, nothing happens. I get no output, even with `--debug`, even when running against chandler's CHANGELOG itself. Any ideas?

### PR DESCRIPTION
**Pull request by mattbrictson**
Fixes #3.

@jhalterman Can you try out this branch at let me know if it works for you?

Just check out the `tag-prefix` branch, run `rake install` to install the gem, and then try running this on your project:

```
chandler push --dry-run --tag-prefix=typetools-
```

### CODE REVIEW

**Comment by jhalterman** [comment]
Sweet - works great! I have one more feature I wanted to raise before you cut a new release or anything. Will post separately.

**Comment by mattbrictson** [comment]
Actually, this may work in a `--dry-run` but I think it is incomplete. The prefix gets stripped off by the time the GitHub API request is made, which means GitHub won't be able to link the release to the correct tag. I'll have to work on this some more. :disappointed:

**Comment by jhalterman** [comment]
It worked for me somehow with this one: https://github.com/jhalterman/typetools/releases/tag/0.4.4

**Comment by mattbrictson** [comment]
Right. The fundamental problem is the mismatch between the tags and the CHANGELOG entries. The tags are in the format "typetools-0.4.4", but the CHANGELOG has "0.4.4". So I'll need to take that into account, which is why I opened #6.

**Pull request merged**
